### ISSUE TITLE
Cosas para fixear para la 2da parte

### ISSUE THREAD

**Issue by nhsz** [rfripp2/fakeMDN#20]
- [x] Hay un [`nav` misterioso](https://github.com/rfripp2/fakeMDN/blob/6a697d24de1b6eb8cb5097bc612f4ca558d26918/index.html#L17). Para qué está?
- [x] Estilar usando clases en lugar de los tags en el css
- [x] Usar el tag `code` y alguna fuente monoespaciada para las secciones de código. Investigar https://highlightjs.org/ para el resaltado de sintaxis
- [x] Sacar los links a las páginas que no están del `index.html`
- [x] Usar el `for ... of` en los ciclos donde no necesitemos usar el índice

**Comment by kriitoboni** [comment]
Ya terminamos todo esto.
